# Generated by Django 5.1.1 on 2024-10-21 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_cabintypes_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveys0',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, db_column='age', null=True)),
                ('gender', models.CharField(db_column='gender', max_length=1)),
                ('q1', models.IntegerField(blank=True, db_column='q1', null=True)),
                ('q2', models.IntegerField(blank=True, db_column='q2', null=True)),
                ('q3', models.IntegerField(blank=True, db_column='q3', null=True)),
                ('q4', models.IntegerField(blank=True, db_column='q4', null=True)),
                ('survey_month', models.CharField(db_column='survey_month', max_length=20)),
                ('arrival_airport', models.ForeignKey(db_column='ArrivalAirportID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_airports', to='system.airports')),
                ('departure_airport', models.ForeignKey(db_column='DepartureAirportID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure_airports', to='system.airports')),
                ('travel_class', models.ForeignKey(db_column='travel_class', on_delete=django.db.models.deletion.DO_NOTHING, to='system.cabintypes')),
            ],
            options={
                'db_table': 'surveys0',
            },
        ),
    ]
