# Generated by Django 5.1.1 on 2024-10-21 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_amenities_amenitiestickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenitiesCabinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenityid', models.ForeignKey(db_column='AmenityID', on_delete=django.db.models.deletion.DO_NOTHING, to='system.amenities')),
                ('cabintypeid', models.ForeignKey(db_column='CabinTypeID', on_delete=django.db.models.deletion.DO_NOTHING, to='system.cabintypes')),
            ],
            options={
                'db_table': 'amenities_cabin_type',
            },
        ),
    ]
