# Generated by Django 5.1.1 on 2024-10-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_amenitiescabintype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenitiescabintype',
            options={'managed': True},
        ),
    ]
