# Generated by Django 5.1.1 on 2024-10-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_amenitiescabintype_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmenitiesCabinType',
        ),
    ]
